version: 2
accept_configuration:
  condition: and
  conditions:
    - condition: property
      property: features
      not_contains_value: Disable
    - condition: property
      property: target.os
      not_equals_value: QNX
    - condition: or
      conditions:
        - condition: property
          property: target.os
          not_equals_value: MacOS
        - condition: property
          property: host.arch
          not_equals_value: ARM64

instructions:
  Build:
  - type: EnvironmentVariable
    variableName: BUILD_DOCUMENTATION
    variableValue: "1"
  - type: Group
    instructions:
        - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
    - type: EnvironmentVariable
      variableName: AM_TIMEOUT_FACTOR
      variableValue: 4
    - type: Group
      instructions:
        - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
      disable_if:
        condition: or
        conditions:
            # this shouldn't be necessary, but the CI non-deterministically freezes when running tst_main,
            # independent of toolchain (MSVC, MingW) or OS version (10, 11)
          - condition: property
            property: host.os
            in_values: ["Windows"]
          - condition: property
            property: target.os
            in_values: ["IOS", "Android", "WebAssembly"]
